#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at appveyor.com
#
#-----------------------------------------------------------------------------

environment:
  matrix:
  - config: Dev
  - config: RelWithDebInfo

shallow_clone: true

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:

# clone directory
clone_folder: c:\projects\osmium-tool

platform: x64

build_script:
  - build-appveyor.bat

artifacts:
  - path: osmium-tool.zip
    name: osmium-tool
